// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCiu9BVclMO-Q8udEF73lUaXoAkjU9opDo',
//     appId: '1:374684794579:web:d7901825ccc53c34b59e26',
//     messagingSenderId: '374684794579',
//     projectId: 'hawshly-1c5db',
//     authDomain: 'hawshly-1c5db.firebaseapp.com',
//     storageBucket: 'hawshly-1c5db.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDbx-Cqpe10_Sunf2fXGi6Ql5Rc1w8wGu8',
//     appId: '1:374684794579:android:e99a3ae1f932bdfbb59e26',
//     messagingSenderId: '374684794579',
//     projectId: 'hawshly-1c5db',
//     storageBucket: 'hawshly-1c5db.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyAErDJD5to7Y6Kz7UUo8mY9dvRVOaJA4e0',
//     appId: '1:374684794579:ios:76f394cad75c1425b59e26',
//     messagingSenderId: '374684794579',
//     projectId: 'hawshly-1c5db',
//     storageBucket: 'hawshly-1c5db.appspot.com',
//     iosBundleId: 'com.example.hawshly',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyAErDJD5to7Y6Kz7UUo8mY9dvRVOaJA4e0',
//     appId: '1:374684794579:ios:acebb99714c32e22b59e26',
//     messagingSenderId: '374684794579',
//     projectId: 'hawshly-1c5db',
//     storageBucket: 'hawshly-1c5db.appspot.com',
//     iosBundleId: 'com.example.hawshly.RunnerTests',
//   );
// }
